{% set version = "2.4.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-longitudinaldata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/longitudinalData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/longitudinalData/longitudinalData_{{ version }}.tar.gz
  sha256: 0cb66260e0171ba8fb31f30ed7609e726ae1187fce8c09aed25ec0ca7c524a8b

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libxfixes           # [linux]
  host:
    - r-base
    - r-class
    - r-clv
    - r-misc3d
    - r-rgl
  run:
    - r-base
    - r-class
    - r-clv
    - r-misc3d
    - r-rgl

test:
  requires:
    - xorg-libxfixes  # [linux]
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda-linux-gnu/sysroot/usr/lib64:${BUILD_PREFIX}/lib $R -e "library('longitudinalData')"  # [not win]
    - "\"%R%\" -e \"library('longitudinalData')\""  # [win]

about:
  home: https://cran.r-project.org/package=longitudinalData
  license: GPL-2.0-or-later
  summary: Tools for longitudinal data and joint longitudinal data (used by packages kml and kml3d).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
